### ISSUE TITLE
QA 录入界面和数据库规划

### ISSUE THREAD

**Issue by carlos-wong** [carlos-wong/SpiderWeb#4]
我们考虑先做一个添加一条QA记录并储存到数据库中的功能。需要考虑一条 QA 会包含什么来设计数据库的表

**Comment by carlos-wong** [comment]
@wangshub

**Comment by wangshub** [comment]
对数据库的设计不太熟悉，我先列一下可能包含的数据吧 @carlos-wong

**Comment by wangshub** [comment]
- QA 索引
- QA 标题
- QA 内容
- QA 项目组信息
- QA 标签
- QA 提出的日期
- QA 截止日期
- QA 提出人
- QA 责任人
- QA 关联的 issue
- QA 完成状态
  - 未分配
  - 已分配
  - 已完成

**Comment by carlos-wong** [comment]
@wangshub 我们这个是测试条目的管理系统。意思是列出测试在测试一个程序的时候需要测试的内容以及期望的结果。并且一个测试的 case 被归属于一次 activity 的。我建议就是有 title, desscription, result, image link, video link, create date, label. 目的是启动一次 test activity 的时候可以快速的选中需要测试的 case

**Comment by carlos-wong** [comment]
@wangshub bug 或者 QA 的 issue 管理我认为 gitlab 已经足够好用 :). 我们做一个补充的周边软件，是给测试人员用的。做为一个筛子，每次改动软件的时候用筛子去过一遍。测试软件是否符合要求。前期我们管理手动的条目。后期考虑加入一些服务的自动化测试。再之后集成到本地有一个本地连接设备自动化测试

**Comment by wangshub** [comment]
是我理解错了 @carlos-wong

**Comment by carlos-wong** [comment]
类似 https://github.com/prove/tarantula 但是他已经不维护了而且使用的是旧的技术。我们做一个狂拽酷帅叼炸天的版本。关键是颜值，颜值即正义 :)

**Comment by carlos-wong** [comment]
@wangshub

**Comment by wangshub** [comment]
@carlos-wong  这个是上次演示那个测试管理:grin: 


_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 OnePlus5 发送_

**Comment by carlos-wong** [comment]
@wangshub 是的，我调查过这类的软件。除了商用的，开源的基本没有一个标杆软件。我们可以尝试做一个

**Comment by carlos-wong** [comment]
数据库表已确定
